CREATE TABLE processed_events (
    event_id      UUID PRIMARY KEY,
    processed_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE dead_letters (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_topic  VARCHAR(200)  NOT NULL,
    message_key   VARCHAR(200),
    payload       VARCHAR(4000) NOT NULL,
    reason        VARCHAR(1000),
    received_at   TIMESTAMP WITH TIME ZONE NOT NULL
);
